InventoryImage:
  #Whether to generate images for the item placeholder
  Item:
    Enabled: true
    #If UseTooltipImage is true, should the plugin attach tooltip image if the target item
    #is just a plain base item with no information worth showing
    UseTooltipImageOnBaseItem: false
    EmbedDisplay:
      Single: "{Item}"
      Multiple: "{Item} x{Amount}"
    AlternateAirTexture: true
  #Whether to generate images for the inventory placeholder
  Inventory:
    Enabled: true
    #Use the player inventory gui template instead of the normal inventory template
    UsePlayerInventoryView: true
    #Whether to render the items a player is holding
    #Only effective when UsePlayerInventoryView is true
    RenderHandHeldItems: true
    EmbedColor: "#55FFFF"
    ShowExperienceLevel: true
  #Whether to generate images for the enderchest placeholder
  EnderChest:
    Enabled: true
    EmbedColor: "#FF55FF"

#Choose what to include in item tooltips
ToolTipSettings:
  ShowDurability: true
  ShowArmorColor: true
  ShowMapScale: true
  ShowFireworkRocketDetailsInCrossbow: true
  ShowAdvanceDetails: true

#Choose what to include when sharing items and inventories to discord
DiscordItemDetailsAndInteractions:
  #Allow users to select items inside an inventory shared to discord
  AllowInventorySelection: true
  #Share filled map details as an image
  ShowMaps: true
  #Share book contents in an interactive book on discord
  ShowBooks: true
  #Show what is inside a container when sharing a container to discord
  ShowContainers: true

HoverEventDisplay:
  #Whether to show hover event text
  Enabled: true
  #Whether to show the cursor image
  ShowCursorImage: true
  #Show information in a tooltip image instead of text
  UseTooltipImage: true
  #Which custom placeholder should have their hover event text ignored
  #This is a list of CustomPlaceholder keys
  IgnoredPlaceholderKeys: []

DiscordAttachments:
  #Images linked from custom placeholder click events (OPEN_URL) are previewed in Discord.
  #When enabled, only websites from the list below are previewed
  RestrictImageUrl:
    Enabled: false
    Whitelist:
      - "https://tenor.com/"
      - "https://i.imgur.com/"
      - "http://i.imgur.com/"
      - "https://storage.googleapis.com/"
      - "http://storage.googleapis.com/"
      - "https://cdn.discordapp.com/"
      - "http://cdn.discordapp.com/"
      - "https://media.discordapp.net/"
      - "http://media.discordapp.net/"
      - "https://textures.minecraft.net/"
      - "http://textures.minecraft.net/"

DiscordCommands:
  #These settings apply to all discord commands below 
  GlobalSettings:
    Messages:
      #Labels must be lowercase
      MemberLabel: "member"
      MemberDescription: "Member to set"
      SlotLabel: "slot"
      SlotDescription: "Slot to choose"
  #Settings for /playerinfo
  PlayerInfo:
    #Enable the /playerinfo command to show player information
    Enabled: true
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    #The description of this command on discord
    Description: "Show player information on discord!"
    #The player information to display
    InfoFormatting:
      Title: "%player_name%'s Player Info"
      SubTitle: "%discordsrv_user_name%"
      WhenOnline:
        - "%vault_prefix%%player_name%"
        - "&7Status: &aOnline"
      WhenOffline:
        - "%vault_prefix%%player_name%"
        - "&7Status: &cOffline"
  #Settings for /resourcepack
  ResourcePack:
    #Enable the /resourcepack command to show installed resource packs on InteractiveChat-Ascension
    Enabled: true
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    #The description of this command on discord
    Description: "Show applied resource packs on discord!"
  #Settings for /playerlist
  PlayerList:
    #Enable the /playerlist command to show all online players in a tablist style image
    Enabled: true
    #The description of this command on discord
    Description: "Show all online players!"
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    #List other players on the same network if connected to bungeecord
    ListBungeecordPlayers: true
    #List only players on servers where InteractiveChat is installed and has info about
    OnlyInteractiveChatServers: true
    #Message to display when no one is online
    EmptyServer: "There are no players online."
    #Delete the tablist message after X seconds (Set to 0 to not have it automatically deleted)
    DeleteAfter: 0
    TablistOptions:
      #The Vanilla Minecraft client caps the maximum players visible
      #on the tablist to the first 80 players
      #Set this to 0 for unlimited
      MaxPlayersDisplayable: 80
      #The minimum width of the player name section of the playerlist
      #This is measured in pixels
      PlayerMinWidth: 0
      SidebarColor: "#999999"
      #The formatting of each player name
      PlayerFormat: "%vault_prefix%%player_name%"
      #Whether to show the player avatar
      ShowPlayerAvatar: true
      #Whether to show player ping
      ShowPlayerPing: true
      #Leave a single blank line to disable
      #PlaceholderAPI placeholders in the header are parsed as THE FIRST PLAYER in the playerlist
      HeaderText:
        - "&aOnline Players ({OnlinePlayers}/100)"
      #Leave a single blank line to disable
      #PlaceholderAPI placeholders in the footer are parsed as THE FIRST PLAYER in the playerlist
      FooterText:
        - ""
      #Instead of parsing color codes for each player name
      #Parse MiniMessage Tags instead
      ParsePlayerNamesWithMiniMessage: false
      PlayerOrder:
        #How should players be ordered in the playerlist
        #.
        #This list is applied from top to bottom
        #If two players are tied in an ordering type
        #The next one will be applied until the bottom
        #If two players are still tied when all ordering types are exhausted
        #The player's full tablist text component and (then) UUID string will be used to ensure consistent ordering
        #.
        #Avalible Ordering Types:
        #GROUP:<group,group...> (Permission group ordered by the provided ordering)
        #PLAYERNAME (Player Name ordering from 0 to 9 then A to Z)
        #PLAYERNAME_REVERSE (Player Name ordering from Z to A then 9 to 0)
        #PLACEHOLDER:<placeholder> (Placeholder ordering from small to large numbers then A to Z)
        #PLACEHOLDER_REVERSE:<placeholder> (Placeholder ordering from Z to A then large to small numbers)
        OrderBy:
          - "GROUP:owner,admin,member,default"
          - "PLACEHOLDER_REVERSE:%luckperms_meta_weight%"
          - "PLAYERNAME"
  #Settings for /item
  ShareItem:
    #Enable the /item command on discord
    Enabled: true
    #Allow the /itemasuser associate command on discord
    AllowAsOthers: true
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    InGameMessage:
      Text: "&6{Player} shared an Item: &f{ItemTag}"
    InventoryTitle: "{Player}'s Item"
  #Settings for /inv
  ShareInventory:
    #Enable the /inv command on discord
    Enabled: true
    #Allow the /invasuser associate command on discord
    AllowAsOthers: true
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    InGameMessage:
      Text: "&6{Player} shared their Inventory: &f[&b{Player}'s Inventory&f]"
      Hover:
        - "&bClick to view!"
    InventoryTitle: "{Player}'s Inventory"
    SkullDisplayName: "&e{Player}"
  #Settings for /ender
  ShareEnderChest:
    #Enable the /ender command on discord
    Enabled: true
    #Allow the /enderasuser associate command on discord
    AllowAsOthers: true
    #Whether this server registers the command with DiscordSRV. If several servers share one bot,
    #set this to true on only one of them.
    IsMainServer: true
    InGameMessage:
      Text: "&6{Player} shared their Ender Chest: &f[&d{Player}'s Ender Chest&f]"
      Hover:
        - "&bClick to view!"
    InventoryTitle: "{Player}'s Ender Chest"

Resources:
  #Which language should be used in places like the item tooltip
  #Visit this page for all the languages that Minecraft offers:
  #https://loohpjames.com/minecraft/languages/
  Language: en_us
  #Apply the force unicode setting to languages and fonts
  ForceUnicodeFont: false
  #Put server resource pack from server.properties
  #at the top of the resource pack ordering list if it is available
  IncludeServerResourcePack: true
  #If ItemsAdder is present and as a resource pack hosted, use its resource pack as server resource pack
  #IncludeServerResourcePack must be true for this setting to be effective
  ItemsAdderPackAsServerResourcePack: true
  #Set this option if you want a separate url as the server resource pack
  #If the URL is empty, the url and hash from server.properties will be used
  #If the hash is empty but URL is not, the resource pack hash will not be checked
  AlternateServerResourcePack:
    URL: ""
    Hash: ""
  #Set which resource pack should be installed and in what order
  #Visit this page for more info:
  #https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/wiki/Resource-Pack
  Order: []
  #Enable (Partial) Optifine Custom Textures CIT support
  OptifineCustomTextures: true
  #Enable (Partial) Chime Custom Model Override support (1.16-1.20.4)
  #Discontinued feature, and is no longer supported or updated
  ChimeOverrideModels: false

Messages:
  ReloadConfig: "&aInteractiveChat-Ascension config has been reloaded!"
  ReloadTexture: "&aInteractiveChat-Ascension reloading textures--- (See console for progress)"
  AccountNotLinked: "&cA Minecraft account must be linked to this Discord account in order to use this command!"
  UnableToRetrieveData: "&cUnable to retrieve data."
  InteractionExpired: "&cThis interaction had expired."
  TrueLabel: "&aTrue"
  FalseLabel: "&cFalse"
  StatusCommand:
    DefaultResourceHash: "&bDefault Resource Hash: %s"
    FontsActive: "&bFonts Active: %s"
    LoadedResources: "&bLoaded Resources: &a"

Settings:
  #This is in seconds
  CacheTimeout: 300
  EscapeDiscordMarkdownFormattingInItems: true
  ReducedAssetsDownloadInfo: true
  #Delete the embed messages sent by InteractiveChat-Ascension after X seconds (Set to 0 to not have it automatically deleted)
  #This does not include ones that have their own config option, such as /playerlist
  EmbedDeleteAfter: 0
  RendererSettings:
    #Threads used to resolve and render block models
    #A positive number sets the absolute number of threads to be used
    #A negative number or 0 sets the number of thread to be used as the logical processor count of your system minus N
    #Defaults to -1 (Number of logical processor in your system - 1)
    RendererThreads: -1

Debug:
  PrintInfoToConsole: false
